{
 "title": "Log Generator Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "# of active goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(log_generator_active_workers)",
     "legendFormat": "Active workers"
    }
   ]
  },
  {
   "title": "Average Storage Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(log_generator_storage_duration_seconds_sum[1m])/rate(log_generator_storage_duration_seconds_count[1m])",
     "legendFormat": "Average Latency"
    }
   ]
  },
  {
   "title": "# of Logs Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(log_generator_logs_generated_total[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Logs Generated Rate by Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (level) (rate(log_generator_logs_generated_total[1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Logs Generated Rate by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (service) (rate(log_generator_logs_generated_total[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Logs Generated Rate per Worker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(log_generator_logs_generated_total[1m]))/sum(log_generator_active_workers)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "# of Storage Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(log_generator_storage_errors_total[1m]))",
     "legendFormat": "Total Storage Errors"
    }
   ]
  }
 ]
}