{
 "title": "Log Ingestor Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Logs Processed Rate by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(log_ingestor_logs_processed_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs Processed Rate by Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (level) (rate(log_ingestor_logs_processed_total[1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Logs Processed Rate by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (service) (rate(log_ingestor_logs_processed_total[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Logs Processed Rate by Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(log_ingestor_logs_processed_total[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}